### ISSUE TITLE
[build] 关于 build.yml的建议

### ISSUE THREAD

**Issue by shenjackyuanjie** [LxHTT/MCSL2#15]
https://github.com/shenjackyuanjie/Difficult-Rocket/actions/workflows/nuitka.yml
可以参考我这里的nuitka构建
建议是nuitka的构建命令每个平台分离，这样可以针对平台进行特殊修改
以及建议单独写一份requrements.txt 提升构建速度

（其实我本来想直接发PR的，但是高一，没时间，先留个issue，有时间了发PR（

**Comment by LxHTT** [comment]
周末我试试

**Comment by lgc2333** [comment]
tried to resolve in #17

**Comment by LxHTT** [comment]
已添加并完善。
