### ISSUE TITLE
BUG｜新Pr引起的第一次启动无法打开

### ISSUE THREAD

**Issue by Casper233** [LxHTT/MCSL2#20]
- [x] 并非电脑自身造成
- [x] MCSL 2 运行在受官方支持的平台上
___

### 一般要素
- 系统：Win11 专业版
- 架构：x86
- MCSL 2 版本：[2023-03-25-17-07](https://github.com/LxHTT/MCSL2/releases/tag/2023-03-25-17-07)

### 问题描述
跑都跑不起来
使用vs看到应当是新的pr的锅

### 复现
直接在无/MCSL2/的目录或没有AutoDetectJavaHistory.txt的情况下打开

### 可能的解决方案（？）
在第一次打开的时候，进行AutoDetectJavaHistory.txt文件的新建，待会看看要不要给改了（

**Comment by LxHTT** [comment]
哈哈哈，我也是发现了，刚修完。

**Comment by LxHTT** [comment]
详见https://github.com/LxHTT/MCSL2/commit/dbdaca950ef3ecf750d9d04d50fd004839a75c2b 处的commit。
