### ISSUE TITLE
BUG｜文件缺失/库不兼容导致GH Actions构建的程序无法启动

### ISSUE THREAD

**Issue by Casper233** [LxHTT/MCSL2#22]
- [x] 并非电脑自身造成
- [x] MCSL 2 运行在受官方支持的平台上
___

### 一般要素
- 系统：Win11 专业版
- 架构：x86
- MCSL 2 版本：[AutoRelease 2023-03-25 14:54:02](https://github.com/LxHTT/MCSL2/releases/tag/2023-03-25-14-54)直到[AutoRelease 2023-03-25 18:21:05](https://github.com/LxHTT/MCSL2/releases/tag/2023-03-25-18-21)均存在
- 并不能确定是否由自身电脑造成

### 问题描述
~~嗨嗨又来了~~
Release版仍然无法打开
但是从GitHub直接git的可以在VS中正常运行

### 复现
下载2023-03-25 14:54到18:21任意版本运行即可

### 可能的解决方案（？）
问题可能存在于[AutoRelease 2023-03-25 14:54:02](https://github.com/LxHTT/MCSL2/releases/tag/2023-03-25-14-54)中，并且在接下来的版本中并没有修复。认为可以对[AutoRelease 2023-03-25 14:54:02](https://github.com/LxHTT/MCSL2/releases/tag/2023-03-25-14-54)中的更改进行逐步排查。

**Comment by LxHTT** [comment]
目前根据本地构建，初步判断为Nuitka所用编译器问题，而不是代码问题。
 - 本地Clang编译不了
 - mingw64正常
 - GitHub Actions可编译但无法正常运行
___
等待最新构建结果。

**Comment by LxHTT** [comment]
还是不行。。。
我翻翻构建日志。。。

**Comment by LxHTT** [comment]
可能是GetFileVersion引入的win32api不兼容且requirements.txt未完善

**Comment by LxHTT** [comment]
已修复。

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
