### ISSUE TITLE
QUESTION log的err！是不是改为 FATAL 更为直观？

### ISSUE THREAD

**Issue by StarryCamile** [LxHTT/MCSL2#47]
- [x] 未在 [Issues](https://github.com/LxHTT/MCSL2/issues) 中看到其他相同疑问
- [x] MCSL 2 运行在受官方支持的平台
___

**Comment by LxHTT** [comment]
是（  
但是日志前缀不对齐难受啊

**Comment by LxHTT** [comment]
所以如果还有别的词语就好了（（
