### ISSUE TITLE
BUG | 强制设置Linux桌面环境变量导致无法运行

### ISSUE THREAD

**Issue by DSHUGUI** [LxHTT/MCSL2#73]
1. 建议新建一个分支，放这个项目 需要用到的文件 用户可以不手动安装额外软件、库
2. 该项目  现在用Ubuntu和Ubuntu上的python解释器  建议测试稳定后把python解释器放在这个分支

4. 以一个目录的形式发布，方便调试单个文件

**Comment by LxHTT** [comment]
请问是源代码无法运行还是打包后的程序无法运行
